### ISSUE TITLE
Regarding com.nvisium.Swift-nV.plist

### ISSUE THREAD

**Issue by maheshmobile** [nVisium/Swift.nV#36]
After login into swift.nv application i cant able to find out the "com.nvisium.Swift-nV.plist" file inside ~/Library/Developer/CoreSimulator/Devices/<some device GUID> /data/library/Preferences

Could you please help me out

Thanks in advance
Mahesh

**Comment by sethlaw** [comment]
Mahesh:

Dealing with the Simulators and fixed locations can be frustrating. Your best bet is to go into the ~/Library/Developer/CoreSimulator/Devices directory and then run a 'find' command to identify what Simulators (and Data Directories) have Swift.nV installed.

Try:

```
find . -name "com.nvisium.Swift*"
```

in that directory and see what happens.

**Comment by maheshmobile** [comment]
i got following result on my terminal

./24ED7893-3784-4272-963D-7ADD3F3B0240/data/Containers/Data/Application/4D198461-2FFB-4C42-B0CF-4AAFF293E077/Library/Caches/com.nvisium.Swift-nV

./24ED7893-3784-4272-963D-7ADD3F3B0240/data/Containers/Data/Application/4D198461-2FFB-4C42-B0CF-4AAFF293E077/Library/Caches/Snapshots/com.nvisium.Swift-nV

./24ED7893-3784-4272-963D-7ADD3F3B0240/data/Containers/Data/Application/4D198461-2FFB-4C42-B0CF-4AAFF293E077/Library/Caches/Snapshots/com.nvisium.Swift-nV/com.nvisium.Swift-nV

./24ED7893-3784-4272-963D-7ADD3F3B0240/data/Containers/Data/Application/4D198461-2FFB-4C42-B0CF-4AAFF293E077/Library/Preferences/com.nvisium.Swift-nV.plist

./24ED7893-3784-4272-963D-7ADD3F3B0240/data/tmp/com.apple.IconsCache/com.nvisium.Swift-nV_CFBundleIcon[15]

**Comment by sethlaw** [comment]
Okay, the identified plist file (#4 in your list) is the one you should be manipulating per the tutorial to explore data storage attacks.

**Comment by maheshmobile** [comment]
I can able to test your swift.Nv application , but how to test my application ,i am having external server not localhost.Thnaks in advance

**Comment by shadyproject** [comment]
@maheshmobile Just replace the 127.0.0.1 in the plist with the IP address of your actual server.  Do this for all entries.

When you start api.rb, you can use the command line flag -o to provide a new IP address for the server to bind, otherwise it will only bind to localhost by default.  Something like 

ruby api.rb -o 192.168.2.1 (assuming that is your IP address)
