### ISSUE TITLE
Unable to login after user registration

### ISSUE THREAD

**Issue by rockpock** [nVisium/Swift.nV#44]
1. I started local server using #ruby api.rb
2. Started the app and all url's in plist are localhost.
3. I'm able to register on app.
4. However I'm to login into app using registered details.
I've attached screenshots for same.
![nv1](https://cloud.githubusercontent.com/assets/24277446/20764765/b088f3b0-b755-11e6-8fb2-c0df7668e65e.png)
![nv2](https://cloud.githubusercontent.com/assets/24277446/20764773/bc7c4ece-b755-11e6-8c07-eb3c17901544.png)

**Comment by Wullschi** [comment]
I solved it by deleting the data model and setting it up again.

1. click on swift_nV.xcdatamodeld in your folder structure
2. Take screenshots from all the entities and attributes that are now displayed in Xcode
3. delete swift_nV.xcdatamodeld
4. Add a new DataModel named swift_nV via File -> New -> File...
5. Add all the entities and attributes again exactly as displayed on your screenshots

**Comment by forced-request** [comment]
@rockpock @Wullschi sorry for the late response. Are both of you on XCode version 8? We're in the process of making Swift.nV compatible with Swift3 and XCode v8 right now.

**Comment by Wullschi** [comment]
Yes, I'm working with XCode 8

**Comment by nVisium-seth-law** [comment]
228cf8e contains multiple fixes, including choice to use only local auth. Fixes this vulnerability.
